import os
import glob

Import('env')
Import('build_dir')

src = ['linact.cpp','linactbuf.cpp']

env.Append(CPPPATH=map(os.path.abspath,glob.glob('.')))

penv = env.Clone()

penv.SharedLibrary('linact', source=src)
penv.Install('../../build', 'linact.dll')
