import os
if os.name == 'nt':
    env = Environment(tools=['mingw'])
else:
    env = Environment()

subdirs = ['lib/linact']

build_dir = "build"

Clean('.', build_dir)

for dir in subdirs:
        print os.path.join(dir, 'SConscript')
        SConscript( os.path.join(dir, 'SConscript'),
            duplicate=0,
            exports = ['env', 'build_dir'])


SConscript('SConscript', variant_dir='build', duplicate=0,
        exports = ['env', 'build_dir'])

