Import('env')
Import('build_dir')
src = ['main.cpp']
libs = ['linact']

libpaths=['#lib/linact','#build']

Clean('.','build')

env.Program(target='linact',CCFLAGS='-g',
        LIBPATH=libpaths,LIBS=libs,source=src)
