import os
if os.name == 'nt':
    env = Environment(tools=['mingw'])
else:
    env = Environment()

subdirs = ['lib/linact']

for dir in subdirs:
        print os.path.join(dir, 'SConscript')
        SConscript( os.path.join(dir, 'SConscript'), exports = ['env'])

build_dir = "build/"
Clean('.', build_dir)

SConscript('SConscript', variant_dir='build',
        duplicate=0, exports = ['env', 'build_dir'])

