import os
if os.name == 'nt':
    env = Environment(tools=['mingw'])
else:
    env = Environment()

build_dir = "build/"
Clean('.', build_dir)

SConscript('SConscript', variant_dir='build',
        duplicate=0, exports = ['env', 'build_dir'])

