Import('env')
src = ['main.cpp']
libs = ['linact']

libpaths=['#lib/linact']

Clean('.','build/')

env.VariantDir('build/', 'src/')
env.Program(target='linact',CCFLAGS='-g',
        LIBPATH=libpaths,LIBS=libs,source=src)
