#ifndef STATUSMSG_H_
#define STATUSMSG_H_
#include "rtos.h"
// Template Author: Henry Herman
// Author email: hherman@mednet.ucla.edu


// This is an autogenerated file.
// It was created by pyelixys.hal.statusfmt
// To ensure proper communication do not modify this file
// UNLESS you really know what you are doing!


#define HEADERCOUNT   1
#define MIXERSCOUNT   4
#define VALVESCOUNT   48
#define THERMOCOUPLESCOUNT   9
#define AUXTHERMOCOUPLESCOUNT   3
#define HEATERSCOUNT   9
#define TEMPERATURECONTROLLERSCOUNT   9
#define SMCINTERFACESCOUNT   2
#define FANSCOUNT   3
#define LINEARACTUATORSCOUNT   5
#define DIGITALINPUTSCOUNT   12
#define LIQUIDSENSORSCOUNT   8



   typedef struct __attribute__ ((__packed__)){
       int period;
       float duty_cycle;
   } MIXER;


   typedef struct __attribute__ ((__packed__)){
       char error_code;
       float temperature;
   } THERMOCOUPLE;

   typedef struct __attribute__ ((__packed__)){
       char error_code;
       float temperature;
   } AUXTHERMOCOUPLE;


   typedef struct __attribute__ ((__packed__)){
       char error_code;
       float setpoint;
   } TEMPERATURECONTROLLER;

   typedef struct __attribute__ ((__packed__)){
       float analog_out;
       float analog_in;
   } SMCINTERFACE;


   typedef struct __attribute__ ((__packed__)){
       int position;
       int requested_position;
       unsigned int error_code;
   } LINEARACTUATOR;


   typedef struct __attribute__ ((__packed__)){
       float analog_in;
   } LIQUIDSENSOR;


   typedef struct __attribute__ ((__packed__)){
        int packet_type;
        unsigned int packet_id;
        int system_error_code;
   } HEADER;

   typedef struct __attribute__ ((__packed__)){
        char error_code;
        MIXER mixer[MIXERSCOUNT]; 
   } MIXERS;

   typedef struct __attribute__ ((__packed__)){
        char error_code;
        short state0;
        short state1;
        short state2;
   } VALVES;

   typedef struct __attribute__ ((__packed__)){
        THERMOCOUPLE thermocouple[THERMOCOUPLESCOUNT]; 
   } THERMOCOUPLES;

   typedef struct __attribute__ ((__packed__)){
        AUXTHERMOCOUPLE auxthermocouple[AUXTHERMOCOUPLESCOUNT]; 
   } AUXTHERMOCOUPLES;

   typedef struct __attribute__ ((__packed__)){
        short state;
   } HEATERS;

   typedef struct __attribute__ ((__packed__)){
        unsigned int error_code;
        TEMPERATURECONTROLLER temperaturecontroller[TEMPERATURECONTROLLERSCOUNT]; 
   } TEMPERATURECONTROLLERS;

   typedef struct __attribute__ ((__packed__)){
        char error_code;
        SMCINTERFACE smcinterface[SMCINTERFACESCOUNT]; 
   } SMCINTERFACES;

   typedef struct __attribute__ ((__packed__)){
        char state;
   } FANS;

   typedef struct __attribute__ ((__packed__)){
        unsigned int error_code;
        LINEARACTUATOR linearactuator[LINEARACTUATORSCOUNT]; 
   } LINEARACTUATORS;

   typedef struct __attribute__ ((__packed__)){
        char error_code;
        unsigned short state;
   } DIGITALINPUTS;

   typedef struct __attribute__ ((__packed__)){
        char error_code;
        LIQUIDSENSOR liquidsensor[LIQUIDSENSORSCOUNT]; 
   } LIQUIDSENSORS;


typedef struct __attribute__ ((__packed__)){
    HEADER header;
    MIXERS mixers;
    VALVES valves;
    THERMOCOUPLES thermocouples;
    AUXTHERMOCOUPLES auxthermocouples;
    HEATERS heaters;
    TEMPERATURECONTROLLERS temperaturecontrollers;
    SMCINTERFACES smcinterfaces;
    FANS fans;
    LINEARACTUATORS linearactuators;
    DIGITALINPUTS digitalinputs;
    LIQUIDSENSORS liquidsensors;
} STATUSPKT;

extern STATUSPKT status;

extern Mutex status_mutex; 

#endif // End statusmsg guard